import { Geist, Geist_Mono, Pixelify_Sans, Press_Start_2P } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  variable: '--font-pixelifySans', 
});

const pressStart = Press_Start_2P({
  subsets: ['latin'],
  weight: "400",
  variable: '--font-pressStart', 
});

export const metadata = {
  title: "Steam Game Search",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pixelifySans.variable} ${pressStart.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
